################################################################################
#   ___   publicplace
#  ¦OUX¦  ‟GNU” “make”
#  ¦Inc¦  compile
#   ---   ‟Coux”
#         makefile
# ©overcq                on ‟Gentoo Linux 13.0” “x86_64”              2015‒1‒6 #
################################################################################
H_make_S_root_path := $(HOME)/moje/programy/‟oux”
H_make_S_compile_path := $(H_make_S_root_path)/compile
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include $(H_make_S_compile_path)/1.mak
include 0.mak
include $(H_make_S_compile_path)/2.mak
################################################################################
