name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'program/**'
    - '*.md'
    - '**/.autoopen-text'
    - '.autoopen-text'
    - '.gitignore'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - '*.md'
    - '**/.autoopen-text'
    - '.autoopen-text'
    - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: packages install
      run: sudo apt-get install libxcb-icccm4-dev libxcb-shape0-dev libxcb-util-dev libxcb-xkb-dev libxkbcommon-x11-dev manpages-dev
    - name: make
      run: PATH="${PATH}:/usr/lib/R/bin" PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib/x86_64-linux-gnu/pkgconfig" make all
