name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: packages install
      run: sudo apt-get install libxcb-icccm4-dev libxcb-shape0-dev libxcb-util-dev libxcb-xkb-dev libxkbcommon-x11-0
    - name: make
      run: PATH="${PATH}:/usr/lib/R/bin" make all
